services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.1
    ports:
      - "5050:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow ui --backend-store-uri /mlflow/mlruns --host 0.0.0.0 --port 5000

  airflow:
    # use current setup or apache/airflow with your dags/scripts mounted
